/home/foxbob/testpy3/openpli-oe-core/meta-openpli/recipes-openpli/enigma2/files/0001-eDVBDB-use-PyExc_TypeError-with-readable-text-and-remove.patch